```{r}
library(oro.dicom)
library(oro.nifti)
slice = readDICOM('IM-0001-0001.dcm')
# d = dim(t(slice$img[[1]]))
image(1:d[1],1:d[2],t(slice$img[[1]]),col=gray(0:64/64))
hdr = slice$hdr[[1]]
hist(slice$img[[1]],breaks = 50,probability = 1,col=rgb(0,0,1, 0.2))
hdr[hdr$name == 'PixelSpacing','value']

all_slices_T1 = readDICOM("T1/")
#all dcm files
nii_T1 = dicom2nifti(all_slices_T1)
d = dim(nii_T1)
#d 512 512 22 [ , , 11]
image(1:d[1],1:d[2],nii_T1[,,11],col = gray(0:64/64))
writeNIfTI(nim = nii_T1, filename = 'fname')

```

```{r}
library(oro.nifti)
readNIfTI(fname = 'fname')
# image(1:d[1],1:d[2],nii_T1[,,11],col = gray(0:64/64))
image(nii_T1,z=11,plot.type = 'single')
image(nii_T1)#plot 22 slices
orthographic(nii_T1,xyz=c(200,220,11))

is_btw_300_400= ((nii_T1>300) & (nii_T1<400))
nii_T1_mask = nii_T1
nii_T1_mask[!is_btw_300_400] = NA
overlay(nii_T1,nii_T1_mask,z=11,plot.type  = "single")
overlay(nii_T1,nii_T1_mask)#from bottom up 
orthographic(nii_T1,nii_T1_mask,xyz=c(200,220,11),text = 'phew', text.cex=15)
# orthographic(nii_T1)
```

