```{r, eval=F,include=F}
rm(list = ls())
library(tidyverse)
library(MRIcloudT1volumetrics)


roiDir = paste0(getwd(),'/data')
file_list = dir(roiDir)
# readSubjectDf(file_list[1])$level

# run it in console
# setwd("C:/Users/lcqi/Desktop/data_analysis_bcaffo_lab/MRI_data_analysis/data")
data = readFileList(fileList = file_list,fixBF = TRUE)
save(data, file = 'raw.rda')


```

```{r}
rm(list = ls())
library(tidyverse)
library(MRIcloudT1volumetrics)

load(file = 'raw.rda')


# convert the rawid to be compatible with the format in lookup table
data$rawid = sapply(strsplit(data$rawid,"_"),function(x) x[1])
data$rawid = as.numeric(data$rawid)

rawdata = na.omit(data)
```

# type 1 level 1
```{r}
table(rawdata %>% filter(type==1,level==1) %>% select(roi))

data = rawdata %>% filter(type==1,level==1) %>% 
  select(rawid,roi,volume) %>% spread(roi,volume) 

# compositional analysis
data = cbind(data[1],prop.table(as.matrix(data %>% select(-rawid)), margin = 1))

# add age/gender

ref = read.csv(paste0(getwd(),'/unrestricted_bcaffo_12_12_2017_12_17_8.csv%3B.csv'), header = T)
colnames(ref)[1] = 'rawid'
data = left_join(data, ref[,c('rawid','Age','Gender')], by="rawid") %>% na.omit
data22 = data %>% filter(Age == '22-25') %>% select(-rawid,-Age,-Gender)
data26 = data %>% filter(Age == '26-30') %>% select(-rawid,-Age,-Gender)
data31 = data %>% filter(Age == '31-35') %>% select(-rawid,-Age,-Gender)
hist(data22 %>% unlist)
# dat = data %>% select(-rawid,-Age,-Gender)
# should we normalize columns?
# dat = apply(dat, MARGIN = 2, FUN = function(i){ scale(i) }) %>% as.data.frame()
```

# permutation test
```{r}
library(gtools)
vec = combinations(3,2,c('data22','data26','data31'))
age_res = list()


for(rho in seq(1e-40,1e-1,length.out = 100)){
  
  
for(i in 1:dim(vec)[1]){
  
  data1 = get(vec[i,1])
  data2 = get(vec[i,2])
  
  # true difference between estimation
  e1 = glasso(cov(data1),rho = rho)$wi
  e2 = glasso(cov(data2),rho = rho)$wi
  tr_diff = e1 - e2
  colnames(tr_diff) = colnames(cov(data1))
  rownames(tr_diff) = colnames(tr_diff)
  index = list()
  
  # only need to compute triangular part
  for(y in 1:(dim(tr_diff)[1]-1)){
    for(x in (y+1):dim(tr_diff)[2]){
      idx = c(y,x)
      if(  
        ((e1[idx[1],idx[2]] * e2[idx[1],idx[2]]) == 0) &
        ((e1[idx[1],idx[2]] + e2[idx[1],idx[2]]) != 0)
         ){index = append(index,list(idx))}
    }
  }
  
  # permutation test
  test = function(data1,data2){
  #shuffle
  data = c(unlist(data1),unlist(data2))
  data = sample(data,replace = F)
  new_data1 = data[1:(dim(data1)[1]*dim(data1)[2])] %>% matrix(nrow=dim(data1)[1],ncol=dim(data1)[2])
  new_data2 = data[(dim(data1)[1]*dim(data1)[2]+1):length(data)] %>% matrix(nrow=dim(data2)[1],ncol=dim(data2)[2])
  perm_diff = glasso(cov(new_data1),rho = rho)$wi - glasso(cov(new_data2),rho = rho)$wi
  colnames(perm_diff) = colnames(data1)
  rownames(perm_diff) = colnames(perm_diff)
  
  return(perm_diff)
  }
  
  n = 5000
  re_diff = replicate(n, test(data1,data2))
  
  # calculate p-values
  # only need to calculate triangular part
  p_matrix = tr_diff * NA
  
  for(idx in index){
    tr_value = tr_diff[idx[1],idx[2]]
    p_matrix[idx[1],idx[2]] = mean(
      abs(tr_value) >= abs(re_diff[idx[1],idx[2],])
      )
  }
  
  
  # for(y in 1:(dim(tr_diff)[1]-1)){
  #   for(x in (y+1):dim(tr_diff)[2]){
  #     index = c(y,x)
  #     tr_value = tr_diff[index[1],index[2]]
  #     for (i in 1:n) {
  #       p_value = mean(abs(tr_value) >= abs(re_diff[,,n][index[1],index[2]]))
  #     }
  #   }
  # }
  # tr_diff = tr_diff * (tr_diff %>% upper.tri())
  
  
}
  if(!(sum(p_matrix<=0.05) %>% is.na)){
    age_res[[paste(vec[i,1],vec[i,2],rho,sep='&')]] = p_matrix
  }
}

```

  

```{r}
temp = glasso(cov(data1),rho = 1e-5)$wi
colnames(temp) = colnames(data1)
rownames(temp) = colnames(temp)

```
```{r}
for(x in dim(temp)){print(x)}
```



# glasso
```{r}
library(glasso)
# lapply(seq(1e-5,1e-1,length.out = 3), function(i){
#   glasso(cov(dat),rho = i)$wi
# })


glasso(cov(dat),rho = 1e-5)$wi

glasso(cov(dat),rho = 1e-5)$wi * (glasso(cov(dat),rho = 1e-5)$wi %>% upper.tri())
```








# garbage code

# gcoda
https://github.com/huayingfang/gCoda
```{r}
source('gcoda.R')
res_gcoda_frac <- gcoda(x = dat,
                        # lambda.min.ratio = 1e-10,
                        counts = F)
print(round(res_gcoda_frac$opt.icov, 2))
print(res_gcoda_frac$opt.index == length(res_gcoda_frac$lambda))
print(res_gcoda_frac$opt.lambda)

# res_gcoda_frac <- gcoda(x = dat,
#                         # lambda.min.ratio = ,
#                         counts = F)
# print(round(res_gcoda_frac$opt.icov, 2))
# print(res_gcoda_frac$opt.index == length(res_gcoda_frac$lambda))
# print(res_gcoda_frac$ebic.score)
```


# test

```{r}
source('gcoda.R')
#-------------------------------------------------------------------------------
# 1 Basic example (no edges in the conditional dependence network)
# 1.1 Generate logistic normal variables
n <- 100;
p <- 20;
x <- matrix(rnorm(n * p), nrow = n); 
x.frac <- exp(x) / rowSums(exp((x)));
totCount <- round(runif(n = n,  min = 1000, max = 2000));
x.count <- x.frac * totCount;
# 1.2 Run gCoda 
# using fraction
res_gcoda_frac <- gcoda(x = x.frac, counts = F);
# using counts
res_gcoda_count <- gcoda(x = x.count, counts = T);
# 1.3 Get the estimation of the inverse covariance matrix
{
  cat("gCoda using fraction data:\n");
  print(round(res_gcoda_frac$opt.icov, 2));
  cat("gCoda using count data:\n");
  print(round(res_gcoda_count$opt.icov, 2));
}
```

