---
output:
  html_document: default
  pdf_document: default
---

```{r, eval=F,include=F}
rm(list = ls())
library(tidyverse)
library(MRIcloudT1volumetrics)


roiDir = paste0(getwd(),'/data')
file_list = dir(roiDir)
# readSubjectDf(file_list[1])$level

# run it in console
# setwd("C:/Users/lcqi/Desktop/data_analysis_bcaffo_lab/MRI_data_analysis/data")
data = readFileList(fileList = file_list,fixBF = TRUE)
save(data, file = 'raw.rda')


```


# type 1 level 1
```{r}
# note function spreadROIs() doesn't work very well
# data = readFileList(fileList = file_list,fixBF = TRUE) %>% spreadROIs()

rm(list = ls())
library(tidyverse)
library(MRIcloudT1volumetrics)

load(file = 'raw.rda')

data = data %>% filter(type==1,level==2) %>% 
  select(rawid,roi,volume) %>% spread(roi,volume) 

# convert the rawid to be compatible with the format in lookup table
data$rawid = sapply(strsplit(data$rawid,"_"),function(x) x[1])

# compositional analysis
# data = data %>% lapply(function(x) as.numeric(x)) %>% as.data.frame
# data = cbind(data[1],prop.table(as.matrix(data[-1]), margin = 1))
# data = data[-1]


# get rid of CSF
# data = data %>% select(-Ventricle)

```




# compositional analysis
```{r}


# only Telencephalon
data = data %>% select(rawid,CerebralCortex_L,CerebralNucli_L,WhiteMatter_L,
                        CerebralCortex_R,CerebralNucli_R,WhiteMatter_R,)

# compositional analysis

# data = data %>% lapply(function(x) as.numeric(x)) %>% as.data.frame
id = data[1]
data = cbind(data[1],prop.table(as.matrix(data[-1]), margin = 1))
data = data[-1]
```

# normalization
```{r}
library(ggplot2)


ggplot(gather(data), aes(value)) + 
    geom_histogram(bins = 10) + 
    facet_wrap(~key, scales = 'free_x')

data = apply(data, MARGIN = 2, FUN = function(i){ scale(i) }) %>% as.data.frame()

ggplot(gather(data), aes(value)) + 
    geom_histogram(bins = 10) + 
    facet_wrap(~key, scales = 'free_x')
```

```{r}
library(glasso)
library(qgraph)
gs = lapply(seq(0,0.1,0.02), function(i){
  qgraph(glasso(cov(data),rho = i),
       labels = colnames(cov(data)),
       # filetype = 'pdf',
       # filename = paste0('rho=',i),
       # layout = matrix(1:12,nrow = 4),
       # DoNotPlot = TRUE,
       details = TRUE,
       directed = TRUE)
})
```



```{r}
library(corrplot)
corrplot(cor(data),
         # addCoef.col = T,
         method = 'color',
         type = 'upper',
         order = 'hclust',
         p.mat = cor.mtest(data, conf.level = .95)$p
         )
# interesting results of Telencephalon
library(randomForest)
lapply(colnames(data), function(i){
  # fml = paste0(i,"~.-",i) %>% as.formula()
  fml = paste0(i,"~.") %>% as.formula()
  data.rf = randomForest(fml, data, importance = TRUE)
  varImpPlot(data.rf,
             main = i)
})
```




# permutation test

```{r}
data = data.frame(id,data)
ref = read.csv(paste0(getwd(),'/unrestricted_bcaffo_12_12_2017_12_17_8.csv%3B.csv'), header = T)
colnames(ref)[1] = 'rawid'

data[1] = as.numeric(unlist(data[1]))
data = left_join(data, ref[,c('rawid','Age','Gender')], by="rawid") %>% na.omit

data_M = filter(data,Gender == 'M')
data_F = filter(data,Gender == 'F')



test = function(x,y){
  l1 = length(x)
  l2 = length(y)
  data = sample(c(x,y),replace = T)
  mean(data[1:l1]) - mean(data[l1:(l1+l2)])
}

sex_res = lapply(2:7, function(i){
  tr_diff = mean(data_M[i] %>% unlist ) - mean(data_F[i] %>% unlist)
  re_diff = replicate(2000, test(data_M[i]%>%unlist, data_F[i] %>% unlist))
  p_value = mean(abs(re_diff)>=abs(tr_diff))
}) %>% do.call(what='cbind') %>% as.data.frame()
colnames(sex_res) = colnames(data)[2:7]

sex_res

t_res = lapply(2:7, function(i){
  p_value = t.test(data_M[i]%>%unlist, data_F[i] %>% unlist)$p.value
}) %>% do.call(what='cbind') %>% as.data.frame()
colnames(t_res) = colnames(data)[2:7]

t_res
```






```{r}
data22 = data %>% filter(Age == '22-25')
data26 = data %>% filter(Age == '26-30')
data31 = data %>% filter(Age == '31-35')
data36 = data %>% filter(Age == '36+')
  
library(gtools)
vec = combinations(4,2,c('data22','data26','data31','data36'))
age_res = list()


test = function(x,y){
  l1 = length(x)
  l2 = length(y)
  data = sample(c(x,y),replace = T)
  mean(data[1:l1]) - mean(data[l1:(l1+l2)])
}

for(j in 1:dim(vec)[1]){
  data1 = get(vec[j,1])
  data2 = get(vec[j,2])
  perm_res = lapply(2:7, function(i){
  tr_diff = mean(data1[i] %>% unlist ) - mean(data2[i] %>% unlist)
  re_diff = replicate(2000, test(data1[i] %>% unlist, data2[i] %>% unlist))
  p_value = mean(abs(re_diff)>=abs(tr_diff))
}) %>% do.call(what='cbind') %>% as.data.frame()
  colnames(perm_res) = colnames(data)[2:7]
  age_res[[paste0(vec[j,1],vec[j,2])]] = perm_res
}

age_res
do.call(rbind.data.frame, age_res)

# cerebralcortex and whitematter change across age
```












# garbage code


# determinant of concentration matrix close to 0
# the matrix is not positive definite ~ singular


```{r,eval=F,include=F}
library(glasso)
library(qgraph)


gs = lapply(seq(0,0.00002,0.000005), function(i){
  qgraph(glasso(cov(data),rho = i),
       labels = colnames(cov(data)),
       # filetype = 'pdf',
       # filename = paste0('rho=',i),
       # layout = matrix(1:12,nrow = 4),
       # DoNotPlot = TRUE,
       details = TRUE,
       directed = TRUE)
})
# layout(matrix(c(1:6),2,3,byrow =TRUE))
# # layout.show()
# plot(gs[[1]])
# plot(gs[[2]])
# lapply(gs, plot)
```


```{r, eval = FALSE}
file.sources = list.files(c("C:/Users/lcqi/Desktop/data_analysis_bcaffo_lab/MRI_data_analysis/muvis"), 
                          pattern="*.R$", full.names=TRUE, 
                          ignore.case=TRUE)
sapply(file.sources,source,.GlobalEnv)
library(tidyverse)
library(psych)

data(bfi)
bfi <- bfi[,1:25]
data = bfi %>% na.omit()
nhanes_dgm <- dgm(data, dtype = "gaussian", alpha = 1e-15, plot = F)

# Find the largest connected component
library(igraph)
grph_clustrs <- clusters(nhanes_dgm$graph)
new_dgm <- induced.subgraph(nhanes_dgm$graph, V(nhanes_dgm$graph)[which(grph_clustrs$membership == which.max(grph_clustrs$csize))])

# Visualize the graph
dgm_vis <- graph_vis(new_dgm, plot = F, directed = T)
dgm_vis <- graph_vis(nhanes_dgm$graph, plot = F, directed = T)
dgm_vis$network

```




